pipeline{
    agent any
    stages{
        stage("Deploy"){
            steps{
            '''
            oc project zcgbyf-deploy-strategies
            oc start-build greeting-service --follow --wait
            '''   
          }
        }
    }
}
